version: '2'
services:
  generatorControl:
    image: 1science/sbt:0.13-oracle-jdk-8
    volumes:
      - ./api:/app
      - ./sbt/generatorControl:/root
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["sbt", "project generatorControl", "run --master-port 2551 --master-num 1 --workers 3 --worker-seeds generatorControl:2551 --dev-port 2552 --dev-seeds generatorControl:2551"]

  mongodb:
    image: mongo:3.3
    volumes:
      - ./mongodb:/data/db

  couchbase-server:
    image: couchbase:community-4.5.1
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091:8091

  database:
    image: couchbase/sync-gateway:1.3.1-community
    volumes:
      - ./database-sync.json:/etc/sync_gateway/config.json
    links:
      - couchbase-server
    ports:
      - 4985:4985

  api:
    image: 1science/sbt:0.13-oracle-jdk-8
    volumes:
      - ./api:/app
      - ./sbt/server:/root
      - ./model_specific:/app/server/model_specific/
    environment:
      - APPLICATION_SECRET=superSecret
    stdin_open: true
    links:
      - mongodb
      - database
    command: ["sbt", "project server", "-Dzeta.actor.cluster.0=generatorControl:2551", "run"]

  webapp:
    image: node:boron
    volumes:
      - ./webapp:/src
    command: "bash -c 'yarn; ./node_modules/.bin/bower install --allow-root; npm run dev'"
    working_dir: /src
    links:
      - database

  proxy:
    image: nginx
    ports:
      - "80:80"
    links:
      - api
      - webapp
      - database
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

